export const expressList = [
	{"id":"ems", "text":"EMS快递"},
	{"id":"shentong","text":"申通快递"},
	{"id":"yuantong","text":"圆通快递"},
	{"id":"zhongtong","text":"中通快递"},
	{"id":"tiantian","text":"天天快递"},
	{"id":"yunda","text":"韵达快递"},
	{"id":"shunfeng","text":"顺丰快递"},
	{"id":"jingdong","text":"京东快递"},
	{"id":"zhaijisong","text":"宅急送"},
	{"id":"pingyou","text":"邮政平邮"},
	{"id":"sure","text":"速尔快递"},
	{"id":"kuaijie","text":"快捷快递"},
	{"id":"debang","text":"德邦物流"},
	{"id":"yousu","text":"优速快递"},
	{"id":"wanjia","text":"万家物流"},
	{"id":"jiayunmei","text":"加运美快递"},
	{"id":"quanfeng","text":"全峰快递"},
	{"id":"quanritong","text":"全日通快递"},
	{"id":"0","text":"其它"}
]